security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        jwt:
            pattern: ^/api  
            stateless: true 
            jwt: ~  

        main:
            stateless: false
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/resservation, roles: ROLE_USER }
        
